version: '3'

services:
    ruby:
        build:
            context: ./services/ruby
            args:
                DOCKER_USER_NAME: ${DOCKER_USER_NAME}
                DOCKER_USER_ID: ${DOCKER_USER_ID}
                DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
        user: ${DOCKER_USER_ID}:${DOCKER_GROUP_ID}
        tty: true
        volumes:
            - '/etc/passwd:/etc/passwd:ro'
            - '/etc/group:/etc/group:ro'
            - './code:/home/code'
    